# Generated by Django 5.0.1 on 2024-01-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facts',
            name='description',
        ),
    ]
